export const SPOTIFY_OAUTH_REQUESTED = 'SPOTIFY_OAUTH_REQUESTED'
export const SPOTIFY_OAUTH_CALLBACK = 'SPOTIFY_OAUTH_CALLBACK'
export const SPOTIFY_OAUTH_SUCCEEDED = 'SPOTIFY_OAUTH_SUCCEEDED'
export const SPOTIFY_OAUTH_FAILED = 'SPOTIFY_OAUTH_FAILED'