export const LOGIN_REQUESTED = 'LOGIN_REQUESTED'
export const LOGIN_CALLBACK = 'LOGIN_CALLBACK'
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED'
export const LOGOUT_SUCCEEDED = 'LOGOUT_SUCCEEDED'
export const LOGOUT_FAILED = 'LOGOUT_FAILED'

export const GET_USER_DATA_REQUESTED = 'GET_USER_DATA_REQUESTED'
export const GET_USER_DATA_SUCCEEDED = 'GET_USER_DATA_SUCCEEDED'
export const GET_USER_DATA_FAILED = 'GET_USER_DATA_FAILED'

export const UPDATE_USER_DATA_REQUESTED = 'UPDATE_USER_DATA_REQUESTED'
export const UPDATE_USER_DATA_SUCCEEDED = 'UPDATE_USER_DATA_SUCCEEDED'
export const UPDATE_USER_DATA_FAILED = 'UPDATE_USER_DATA_FAILED'

export const GET_LOCATION_DATA_REQUESTED = 'GET_LOCATION_DATA_REQUESTED'
export const GET_LOCATION_DATA_SUCCEEDED = 'GET_LOCATION_DATA_SUCCEEDED'
export const GET_LOCATION_DATA_FAILED = 'GET_LOCATION_DATA_FAILED'